### ISSUE TITLE
Proposal: npm module + cli

### ISSUE THREAD

**Issue by twilson63** [unframework/html2hyperscript#2]
Hey Nick,

If you want to make this project a npm module and cli tool, I will be happy to submit a pull request, then I can point the html2hscript web app to this module, and we would have one parser code base to manage.  What do you think?

Thanks

Tom

**Comment by unframework** [comment]
Sounds good, thanks for suggesting!

**Comment by unframework** [comment]
FYI, I have done some of the splitting of the CLI vs main module code. I double-checked against your repo for reference, but did things a bit differently (using a simple return value instead of a callback in main module interface).

**Comment by unframework** [comment]
Finished the split and added some test coverage.

**Comment by twilson63** [comment]
Awesome

I will point the web app to your lib!

Thx

Tom

Sent from my iPhone

On Mar 17, 2015, at 4:12 PM, Nick Matantsev notifications@github.com
wrote:

Closed #2 https://github.com/unframework/html2hyperscript/issues/2.

—
Reply to this email directly or view it on GitHub
https://github.com/unframework/html2hyperscript/issues/2#event-257358457.
